Attempt to fix lyrics clash with album merges
Traceback (most recent call last):
File "/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/bin/.beet-wrapped", line 9, in <module>
sys.exit(main())
~~~~^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/ui/__init__.py",
line 968, in main
_raw_main(args)
~~~~~~~~~^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/ui/__init__.py",
line 948, in _raw_main
subcommand.func(lib, suboptions, subargs)
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/ui/commands/import_/__init__.py",
line 132, in import_func
import_files(lib, byte_paths, query)
~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/ui/commands/import_/__init__.py",
line 76, in import_files
session.run()
~~~~~~~~~~~^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/importer/session.py",
line 248, in run
pl.run_parallel(QUEUE_SIZE)
~~~~~~~~~~~~~~~^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/util/pipeline.py",
line 479, in run_parallel
raise exc_info[1].with_traceback(exc_info[2])
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/util/pipeline.py",
line 337, in run
out = self._run_in_context(self.coro.send, msg)
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/util/pipeline.py",
line 246, in _run_in_context
return self.ctx.run(func, *args)
~~~~~~~~~~~~^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/util/pipeline.py",
line 215, in coro
func(*args, task)
~~~~^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/importer/stages.py",
line 257, in plugin_stage
func(session, task)
~~~~^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/plugins.py",
line 317, in wrapper
return func(*args, **kwargs)
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beetsplug/lyrics.py",
line 1139, in imported
self.add_item_lyrics(item, False)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beetsplug/lyrics.py",
line 1185, in add_item_lyrics
elif item_key in item:
^^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/dbcore/db.py",
line 558, in __contains__
return key in self.keys(computed=True)
~~~~~~~~~^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/library/models.py",
line 835, in keys
if with_album and self._cached_album:
^^^^^^^^^^^^^^^^^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/library/models.py",
line 761, in _cached_album
self.__album.load()
~~~~~~~~~~~~~~~~~^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/dbcore/db.py",
line 646, in load
self.__dict__.update(self.get_fresh_from_db().__dict__)
~~~~~~~~~~~~~~~~~~~~~~^^
File
"/nix/store/gwsddaldpxas8d5q00jxdkm6a7m5s5rg-python3.14-beets-2.12.0/lib/python3.14/site-packages/beets/dbcore/db.py",
line 350, in get_fresh_from_db
raise NotFoundError(f"No matching {model_cls.__name__} found") from None
beets.dbcore.db.NotFoundError: No matching Album found